import LayoutContainer from "@/components/layout/LayoutContainer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Zenmi baby",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Create a client

    return (
        <html lang="en">
            <LayoutContainer>
                {children}
            </LayoutContainer>
        </html>
    );
}
